#!/usr/bin/env python3
"""
Generate patch_context.md for an incident: related source files, SQL, HOTFIX pointers (skeleton).

Usage:
  python scripts/generate_patch_context.py --incident debug_evidence/2026-05-11-example
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path


def repo_root() -> Path:
    return Path(__file__).resolve().parent.parent


KEYWORD_FILES: list[tuple[str, frozenset[str], str]] = [
    ("vector / match RPC", frozenset({"vector", "malformed array", "pgvector", "get_safe_matches"}), "db_service.py, sql/match_logic.sql, fox_logic.py"),
    ("hydration / DOM", frozenset({"hydration", "<p>", "descendant", "nested"}), "fox_quiz/, match_wall.py, Reflex layout components"),
    ("RPC / PostgREST", frozenset({"pgrst", "postgrest", "rpc", "function"}), "db_service.py, sql/match_logic.sql, sql/DEPLOY_LOG.md"),
    ("async / state", frozenset({"immutablestate", "asyncio", "await", "coroutine"}), "fox_quiz/ state handlers, DEBUG_GUIDE.md §7"),
]


def read_text(path: Path, limit: int | None = None) -> str:
    if not path.is_file():
        return ""
    t = path.read_text(encoding="utf-8", errors="replace")
    if limit:
        return t[:limit]
    return t


def extract_hotfix_titles(backlog: str) -> list[str]:
    titles: list[str] = []
    for m in re.finditer(r"^###\s+(HOTFIX:.+)$", backlog, re.MULTILINE):
        titles.append(m.group(1).strip())
    return titles[:25]


def build_context(incident: Path, root: Path) -> str:
    bundle = ""
    for name in ("backend.txt", "console.txt", "root_cause.md", "rpc.sql"):
        bundle += read_text(incident / name, 8000).lower()

    matched: list[str] = []
    for label, kws, files in KEYWORD_FILES:
        if any(kw in bundle for kw in kws):
            matched.append(f"- **{label}** → `{files}`")

    if not matched:
        matched.append("- (no keyword hit) → review full incident + DEBUG_GUIDE.md manually")

    backlog_path = root / "BACKLOG.md"
    backlog = read_text(backlog_path)
    hotfixes = extract_hotfix_titles(backlog)
    hf_lines = "\n".join(f"  - {h}" for h in hotfixes) if hotfixes else "  - (none parsed)"

    rel = incident.relative_to(root)
    return f"""# Patch context (auto-generated skeleton)

**Incident directory**: `{rel}`

## Likely related areas (keyword heuristic)

{chr(10).join(matched)}

## SQL / deploy trail

- `sql/match_logic.sql` — RPC source of truth for match vector path
- `sql/DEPLOY_LOG.md` — what was applied in Supabase

## Historical HOTFIX titles (from BACKLOG.md)

{hf_lines}

## Suggested human steps

1. Run `python -m ai.diagnosis.root_cause_engine --incident {rel}` for taxonomy-ranked guess.
2. Run `python -m ai.replay.replay_incident --incident {rel}` (mock) before any live replay.
3. Follow `docs/AI_PATCH_FLOW.md` — human review required before deploy.

_Last generated by scripts/generate_patch_context.py_
"""


def main() -> None:
    root = repo_root()
    p = argparse.ArgumentParser(description="Write patch_context.md next to incident evidence (skeleton).")
    p.add_argument("--incident", type=Path, required=True)
    args = p.parse_args()
    incident = args.incident.resolve()
    if not incident.is_dir():
        sys.exit(f"error: not a directory: {incident}")

    md = build_context(incident, root)
    out = incident / "patch_context.md"
    out.write_text(md, encoding="utf-8")
    print(f"Wrote {out.relative_to(root)}")


if __name__ == "__main__":
    main()
